package com.spring.model;
// Generated 26-Dec-2019 21:44:52 by Hibernate Tools 4.3.1



/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private int id;
     private String name;
     private Integer qty;
     private Double price;
     private String img;

    public Product() {
    }

	
    public Product(int id) {
        this.id = id;
    }
    public Product(int id, String name, Integer qty, Double price, String img) {
       this.id = id;
       this.name = name;
       this.qty = qty;
       this.price = price;
       this.img = img;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public String getImg() {
        return this.img;
    }
    
    public void setImg(String img) {
        this.img = img;
    }




}


